### ISSUE TITLE
add support for TextInputlayout?

### ISSUE THREAD

**Issue by kamilwlf** [thyrlian/AwesomeValidation#13]
add support for TextInputlayout?

**Comment by thyrlian** [comment]
Thanks @kamilwlf 

Yes, I'd like to support **TextInputLayout**.  But since using **TextInputLayout** is different than using **EditText** (EditText should be wrapped in TextInputLayout), if I want to make it happen, I might have to change the library's architecture and some of the APIs.  The other fact is TextInputLayout has built-in floating label feature, so I have to disable my own UNDERLABEL style for it.

Anyway, I'll think about it when time allows.

**Comment by thyrlian** [comment]
Hi @kamilwlf , sorry for the long waiting.  But I've been working on this feature last weekend, and just merged the feature branch to master.  It's well unit tested, and I plan to release it soon after updating README.  It would be great if you could try it out and tell me what else is missing or not working there.  Thanks in advance.

**Comment by thyrlian** [comment]
Implemented by https://github.com/thyrlian/AwesomeValidation/pull/29
