### ISSUE TITLE
when EditText show validation error tooltip in pager

### ISSUE THREAD

**Issue by boomsya** [thyrlian/AwesomeValidation#15]
hi!

i have 2 pages. and i can scroll page to left and after that i have see second page

when i scroll - validation tooltip sticky to the left side of screen

i have attached img
![pic_2](https://cloud.githubusercontent.com/assets/8008462/11811526/a05df728-a33e-11e5-9099-addaca9798a3.png)
![pic_3](https://cloud.githubusercontent.com/assets/8008462/11811527/a06366ea-a33e-11e5-850f-dc324c933b19.png)
![pic_4](https://cloud.githubusercontent.com/assets/8008462/11811528/a06604c2-a33e-11e5-86d4-5b8dab95a356.png)

**Comment by thyrlian** [comment]
Hi @boomsya , thanks for using AwesomeValidation and your valuable feedback.

Please correct me if I get it wrong:
I assume that you are using ViewPager, and I think you want to dismiss the sticky tooltip when scrolling to the other page.  Then could you try to call `mAwesomeValidation.clear();` when `ViewPager.onScrollChanged`?

Because to me, each developer's implementation differs, I can't guess beforehand what listener I should register the clear method to.

**Comment by boomsya** [comment]
sorry for not good English :)
yes, you right

can tooltip slide(move) with TextEdit synchronous over screen? 

but your answer really help me too

**Comment by thyrlian** [comment]
No problem :)

Now I completely understand the problem: **the tooltip doesn't move along with the screen**.

Hmmm, I'm afraid that we could do nothing about it.  Since the tooltip is from Android's code: `EditText.setError(CharSequence error)`.  You can check this [line](https://github.com/thyrlian/AwesomeValidation/blob/master/library/src/main/java/com/basgeekball/awesomevalidation/validators/BasicValidator.java#L15) here.

So I guess you'd better clear the validation onScrollChanged.  But please be careful, only clear when you're sure the 2nd page is ready, not when user by accident move several pixels left or right.

Thanks and good luck :)

**Comment by boomsya** [comment]
thanks for helping to me

can i ask just one question?
i have EditText fields and when user clear (for example) seond field - i have event:
yourage_input.addTextChangedListener(new TextWatcher() {
            public void afterTextChanged(Editable s) {
                mAwesomeValidation.validate();   <<<<----------------- 
            }
            public void beforeTextChanged(CharSequence s, int start, int count, int after){}
            public void onTextChanged(CharSequence s, int start, int before, int count){}
        });

but user can delete text in first field, and go to second and delete text in second 
and after that his enter valid number in first field and mAwesomeValidation.validate() return to me FALSE because second field empty (i added validator RegexTemplate.NOT_EMPTY)

can i check validation for concrete field? (when user fill first field valid - i should need set seekbar value from field)
i have fouded function "checkFields" but they check all ArrayList

**Comment by thyrlian** [comment]
Sorry that I just got time to read your comments.

To answer your question:
* I didn't think about validating fields one by one, that's why the ***checkFields*** method you found iterates all.
* The reason I did it this way is because I believe that validating all fields at once is the most common use case.  But you're right, sometimes we just want to trigger validation of one single field on its input change.
* For the time being (based on current implementation), I think you did it right: instantiating one AwesomeValidation object per field, and validate them isolatedly.

Have fun playing with it :)
