### ISSUE TITLE
mAwesomeValidation.validate()

### ISSUE THREAD

**Issue by hafsalrahman** [thyrlian/AwesomeValidation#25]
` if (mAwesomeValidation.validate()) { `
//awsome validator implemented inside fragment, gives below error

> Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference

**Comment by thyrlian** [comment]
Could you please try to debug your app?  It seems like one of your `EditText` being validated is somehow null.

**Comment by hafsalrahman** [comment]
I debugged and it seems fine, note: my fragments are inside View pager

**Comment by thyrlian** [comment]
Sorry, I could not really tell you what the problem is without debugging the code from my side.  My thinking: using ViewPager should be OK; fragment is also mine (the demo also uses EditText inside fragment).  Maybe it's because of some Android lifecycle method causes the EditText being null at some point?  I understand you mentioned your EditText is not null during debugging.  But it might be some later point or so...

**Comment by hafsalrahman** [comment]
Now it is working fine when I updated my code. 
## For your info 

> moved  ` mAwesomeValidation.addValidation(` code lines  to ` onViewCreated(View view, @Nullable Bundle savedInstanceState) {` 
> from 
> `onCreateView(LayoutInflater inflater, ViewGroup container,Bundle savedInstanceState) {, 
> `

**Comment by thyrlian** [comment]
Aha, this change makes sense.  Good to hear now it works for you :)
