### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by rafaeltoledo** [thyrlian/AwesomeValidation#3]
This would be awesome to help developers to keep the library updated in their projects.

**Comment by thyrlian** [comment]
Obrigado Rafael :)

Yes, I'm very happy to do so.  But before doing this, I'd like to fix the unit test structure under gradle (e.g. command line execution), or maybe plus something else I could fix / add in a short time.

**Comment by MiguelCatalan** [comment]
How is this going? I'm very interested to see it at Maven Central :blush:

**Comment by thyrlian** [comment]
Gracias Miguel.  Actually I'm still working on it, and have some problem with publishing it to Maven Central (e.g. I don't own the domain of the lib package name, so that I have to refactor it).  But I promise I'll try to make it in the next few days :) 

Here is the ticket regarding Maven Central publishing.
[https://issues.sonatype.org/browse/OSSRH-14310](https://issues.sonatype.org/browse/OSSRH-14310)

**Comment by thyrlian** [comment]
Just updated README, now it's fully working from JCenter, you could try adding below to your gradle's dependencies:
```java
compile 'com.basgeekball:awesome-validation:1.0'
```

**Comment by thyrlian** [comment]
Will publish to Maven Central:
https://issues.sonatype.org/browse/OSSRH-68174
