### ISSUE TITLE
Custom Validators?

### ISSUE THREAD

**Issue by mikecoppola16** [thyrlian/AwesomeValidation#32]
So I can a add param as a class to handle complex validation? If not is there a way to validate age from a date string such as 10/20/1985?

**Comment by thyrlian** [comment]
Initially, I thought if someone use `DatePicker`, the number / date selected from there should always be valid by itself.  But in your case, if you want to validate the age based on a String, I guess you could use Regex to check if the year is less than 19xx, if equals 19xx, month and date should be earlier than some date.  Actually this is a bit too trivial, I need to think about this scenario.  Sorry for that.  What do you think?  And could you attach an example UI please?  Thanks.

**Comment by podybman** [comment]
You might want to validate date1 < date2 < now for example

**Comment by thyrlian** [comment]
Need more details.

If it's not a `DatePicker`, what would it be?

1. A `EditText` with `android:inputType="date"`.  This only guarantees the numeric keyboard, but the input result could still be any non-date format / order.  In that case, the validation process would be:
    * Check if it's valid date type, when not -> throw error: "Not a date format";
    * When yes, convert it to [`Date`](https://developer.android.com/reference/java/util/Date.html) object;
    * Compare the `Date` object with the given criteria (I guess it should be an age?).  And there should be a helper method created, to provide something like: `boolean SomeHelperClass.isOldEnough(Date someDate, int age)`.  And again, when not, throw another different error message "You are not old enough to do that".

2. Multiple `EditText`s, each of them takes care of day / month / year separately.  Finally when validation is triggered, it needs to validate their input one by one, then group them together as a `Date`, finally it would be just the same steps like above.

What I mean is, the validation steps could be quite different, according to different UI designs.  And I don't think there is any best practice of how you should design that, except the standard `DatePicker`.

@podybman @mikecoppola16 could you please provide your UI design, so that I can think about it?  Thank you very much.  Hope we can figure it out.

**Comment by AminMahboubi** [comment]
You can! Try to use the CustomValidation with your own validation.
This is how:

`mAwesomeValidation.addValidation(activity, R.id.edt_birth, new CustomValidation() {
    @Override
    public boolean compare(String input) {
        try {
            new SimpleDateFormat("dd/MM/yyyy", Locale.US).parse(input);
            return true;
        } catch (Exception e) { return false;}
        return false;
    }
}, R.string.err_birth);`

**Comment by thyrlian** [comment]
[PR](https://github.com/thyrlian/AwesomeValidation/pull/53) is merged to master.
