### ISSUE TITLE
TextInputLayout validation doesn't work.

### ISSUE THREAD

**Issue by rajeshkumarkhadka** [thyrlian/AwesomeValidation#35]
It doesn't work with the TextInputLayout validation.
Implementation:
`
**Java Code** 
```
AwesomeValidation awesomeValidation = new AwesomeValidation(ValidationStyle.TEXT_INPUT_LAYOUT);

awesomeValidation.addValidation(getActivity(), R.id.test_til_email,Patterns.EMAIL_ADDRESS, R.string.error_email);

 awesomeValidation.validate()
```

**XML*
```
<android.support.design.widget.TextInputLayout
        android:id="@+id/test_til_email"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <EditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="enter email" />
    </android.support.design.widget.TextInputLayout>
```

**Comment by thyrlian** [comment]
Could you please provide more details?  E.g. layout xml, code, screenshot?  Thanks.

**Comment by rajeshkumarkhadka** [comment]
@thyrlian I have updated above. Please have a look above.

**Comment by thyrlian** [comment]
Thanks @rajeshkumarkhadka.  Could you please tell me what's exactly wrong with the behavior?  Any log?  Any screenshot?  Does the `getActivity()` return the right activity back?  How do you trigger the `awesomeValidation.validate()` (in some onClickListener)?

**Comment by obernal** [comment]
I'm seeing this problem too while testing validation with TextInputLayout. `getActivity()` returns the right activity as it is the Fragment's `getActivity()` method. Perhaps the problem is using the library from inside a fragment? 

As to what are the symptoms of it not working, basically the problem is `mAwesomeValidation.validate()` is always true despite having added the proper validation so obviously no error message is displayed. 

I've tried the following:
On Fragment's `onCreateView()`
```java
mAwesomeValidation = new AwesomeValidation(ValidationStyle.TEXT_INPUT_LAYOUT);
mAwesomeValidation.addValidation(getActivity(), R.id.usernameWrapper, Patterns.EMAIL_ADDRESS, R.string.err_email);
```
The Fragment implements `OnClickListener` and checks whether `mAwesomeValidation.validate() == true` whenever a button inside the fragment is clicked. The result is always true. Any help is really appreciated!

```java
    @Override
    public void onClick(View v) {
        if (mAwesomeValidation.validate() == true) {
            //It's always executing this code even though the fields have validation issues.
        }
    }
```

**Comment by thyrlian** [comment]
Thanks @obernal for sharing your ideas.

* Actually fragment is not a problem, I use it also in the [demo](https://github.com/thyrlian/AwesomeValidation/blob/master/demo/src/main/res/layout/activity_demo.xml#L52) app
* Good to know that the `activity` passed in is the right one, when not sure, better check with debugger
* I remember now that someone else also had a similar problem - always return true on `validate()`.  That was because of placing the `addValidation` in the wrong lifecycle call.  Please try with some point after `onCreateView` to see if the problem still exists or not.

**Comment by rajeshkumarkhadka** [comment]
@thyrlian I have used fragment's ```onCreateView``` method. I didn't find any logs related to the library.

**Comment by thyrlian** [comment]
Thanks @rajeshkumarkhadka. Would you please try move the code to another place other than `onCreateView` (something later)?

**Comment by rajeshkumarkhadka** [comment]
@thyrlian works on ```onActivityCreated``` 👍 .

**Comment by thyrlian** [comment]
@rajeshkumarkhadka cool, glad to hear it's working now.  As said before, if the activity is OK, most likely the view to be validated is not available yet at the given lifecycle call.

**Comment by pixma** [comment]
I am trying to use this library with - 

support.design.widget.CoordinatorLayout as Root Layout.

EditText is wrapped by TextInputLayout and there is no fragment implemented.
Its just in One simple activity and its crashing at "validate()" method

Msg monitor shows:
"invoke virtual method 'void android.support.design.widget.TextInputLayout.setError(java.lang.CharSequence)' on a null object reference"

I guess Still not fixed or This library is meant to be used with Fragments only?

**Comment by thyrlian** [comment]
@pixma 
* From the README's sample code, you'll find below instruction:
```
// to validate TextInputLayout, pass the TextInputLayout, not the embedded EditText
AwesomeValidation mAwesomeValidation = new AwesomeValidation(TEXT_INPUT_LAYOUT);
mAwesomeValidation.addValidation(activity, R.id.til_email, Patterns.EMAIL_ADDRESS, R.string.err_email);
```
* From the demo app, this library works perfectly with both activity and fragment.
* According to your log, it seems like the `TextInputLayout` you passed in is somehow null.  Please try to debug about this object.

**Comment by lokendra45** [comment]
Cannot resolve method 'addValidation(androidx.fragment.app.FragmentActivity, int, int)' . Error Throw
