### ISSUE TITLE
Add option to clear individual error on text changed

### ISSUE THREAD

**Issue by Pinaki93** [thyrlian/AwesomeValidation#41]
I'm using `ValidationStyle.UNDERLABEL` as my validation style. 

Now as far as I could explore , I could find a method to clear error from all the form fields:
`mAwesomeValidation.clear();`

However, I am not able to remove error from a single EditText. My requirement is, when a user starts typing in an EditText field, it should remove the under label error. I've tried using `setError(null)` on the EditText but it isn't working. Is there any way to do this?

**Comment by thyrlian** [comment]
Hi @Pinaki93, thanks for the feedback.

I understand what you mentioned above, but unfortunately it's not supported so far.  It's about UX, different people might have different opinion.  I think it's OK that I've chosen clear all as default instead of clear individual.  But it's my fault if I don't provide clear individual as an option.  Sorry for that.  I'll put this to my TODO list.

I would like to rephrase the title from "Remove validation error" to "Add option to clear individual error on text changed".  Then for the `mAwesomeValidation` instance, you can set the option as enabled, so that error removal code will be added to `addTextChangedListener` for each individual input field.

Thanks again.

**Comment by thyrlian** [comment]
This feature has been added to TODO list.

**Comment by jsneo** [comment]
Have managed to do a quick workaround by clearing and validating the EditText on focus change.
`@OnFocusChange(R.id.text_business_name)
    public void changeBusinessNameFocus()
    {
        revalidate();
    }
    
    @OnFocusChange(R.id.text_address)
    public void changeAddressFocus()
    {
        revalidate();
    }
    
    public void revalidate()
    {
        awesomeValidation.clear();
        awesomeValidation.validate();
    }`

**Comment by thyrlian** [comment]
Implemented by [commit](https://github.com/thyrlian/AwesomeValidation/commit/98dd5286a69e1d79aad8e5e0b2c1a955e9256c9e).

I didn't provide an option, just do this by default.  Because I've checked the default behaviour of `EditText.setError("...")`, it disappear on text changed.

**Comment by thyrlian** [comment]
Did this for both UnderlabelStyle and ColorationStyle.
