### ISSUE TITLE
Validation of Spinner/Spinner selection

### ISSUE THREAD

**Issue by lordplagus02** [thyrlian/AwesomeValidation#57]
Is it possible to validate a spinner widget directly? Trying to make sure the user selects an item from the dropdown before the form can be submitted.

Maybe I should use an invisible EditText? Or is there a more elegant solution?
Passing the spinner to the validation method by Id seems to compile and run, but nothing actually happens (which I kind of expected).

**Comment by thyrlian** [comment]
Hi @lordplagus02 sorry that validation of spinner is not supported so far.  Initially I thought spinner always have valid options provided by developer (but didn't think about the empty case).

I'll think about it to see if I can add this feature soon or not.  Thanks.

**Comment by thyrlian** [comment]
Implemented by [commit](https://github.com/thyrlian/AwesomeValidation/commit/a25ce13b40c3fb44e9571f2bcbb5488a70a56765).

**Comment by thyrlian** [comment]
Now I've provided a completely flexible way of validating `Spinner`, or any kind of `View`.

You can simply do:

```java
addValidation(View view, CustomValidation customValidation, CustomValidationCallback customValidationCallback, CustomErrorReset customErrorReset, String errMsg)
```

or

```java
addValidation(Activity activity, int viewId, CustomValidation customValidation, CustomValidationCallback customValidationCallback, CustomErrorReset customErrorReset, int errMsgId)
```

The reason why I made so many custom code blocks, ask you to define on your own, is because of:

* It's flexible, can apply to any `View`;
* As you can see from this [thread](https://stackoverflow.com/questions/867518/how-to-make-an-android-spinner-with-initial-text-select-one), there is no generic or best way to set a default hint or blank value for `Spinner`.  Different people may develop in different approach.  And what's more, to set error to `Spinner`, extract text from `Spinner`'s adapter may be different as well.

Will release the binary ASAP.
