### ISSUE TITLE
Validation working for only the first identical fragment

### ISSUE THREAD

**Issue by myeduapp** [thyrlian/AwesomeValidation#65]
I have a activity where number of identical fragments are present with each having TextInputLayout validation.

I am having below code in each fragment.

```
@Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        mAwesomeValidation.addValidation(getActivity(), R.id.til_exam_name, Constants.REQUIRED_EXPRESSION, R.string.err_exam_name);
        mAwesomeValidation.addValidation(getActivity(), R.id.til_out_of, Constants.REQUIRED_EXPRESSION, R.string.err_out_of);
    }
    public boolean validateInput(){
        if(mAwesomeValidation.validate()){
            return true;
        }
        return false;
    }
```

Fragments are iterated and validated with below code:

```
List fragments = getActivity().getSupportFragmentManager().getFragments();
            for (int i = 0; i < fragments.size(); i++) {
                Fragment a = (Fragment) fragments.get(i);
                View resultview = a.getView();
                String ab = a.getClass().toString();
                if (ab.contains("RepSubMarkTemplate")) {
                    FragmentRepSubMarkTemplate frag= (FragmentRepSubMarkTemplate) a;
                    if(!frag.validateInput()){
                        isValid=false;
                        continue;
                    }
```

But validation is performed only on first fragment.

How to handle this issue??

**Comment by thyrlian** [comment]
The library is fully capable of handling views from multiple fragments, just like the [example in demo project](https://github.com/thyrlian/AwesomeValidation/blob/master/demo/src/main/res/layout/activity_demo.xml#L53-L63).

And the reason why it doesn't work for your case, is as you addressed: **identical resource ids**.

Sorry to tell, but it's by design.  I didn't think about such case at all.

But what I would recommend is, maybe you can try: instead of passing resource id, when you have the access of the current fragment, get the subview (which has identical resource id), and pass the view object as a param to the `addValidation` method.
