### ISSUE TITLE
Problem when using another language..

### ISSUE THREAD

**Issue by SunilThombare** [thyrlian/AwesomeValidation#66]
The validation from a-z or A-Z is not working when using another language input. Which does not contain these alphabets. 
Please help
SUNIL THOMBARE, INDIA, Pune +91-9423009650

**Comment by thyrlian** [comment]
Sorry to hear that.  But could you be more specific how to reproduce the issue.  Would be great to show some code snippet, or even the project repository if possible.  Thanks.

**Comment by SunilThombare** [comment]
Thanks a lot lot lot for your so so so quick response. Really overwhelmed
with your response. The first and foremost thing I would like is to
CONGRATULATE for the awesome work that you have done for the developers, (I
am a novice). The problem that I have faced is that just :

in the validation designed by you we can use only ENGLISH alphabets and
special characters. Suppose I change the language of the app and try to
input the alphabets used in that language (for example "How are you" in
ENGLISH is equal to "तू कसा आहेस" in my language, as these characters are
not in our awesomevalidation, it does not recognize these characters and
produces an ERROR.

This is my problem. Thanks once again very very much.

SUNIL +91-9423009650

**Comment by thyrlian** [comment]
Thanks a lot for your compliment, and I really appreciate your feedback.

Sorry about my knowledge in Marathi, have you tried building your own regex to validate the user input, instead of using the built-in ones?  **And in order to match Marathi charaters, you need to check specified Unicode block.**  Please google `marathi regex` or `unicode regex` for more examples.  This library just helps you build your validation system, the real validation job will be done by Java, as long as you provide a valid regex, it should work.  The problem is not on the library side, but you need to build a working regex.

Please try something like:
```java
mAwesomeValidation.addValidation(activity, R.id.edt_name, "[YOUR_MARATHI_REGEX]", R.string.err_name);
```

Let me know how it works.  Thanks.

**Comment by SunilThombare** [comment]
Thanks a lot, Sir, you are perfectly right, the solution WORKED.
Thanks a lot again.

**Comment by thyrlian** [comment]
Good to hear it's working for you :)

**Comment by SunilThombare** [comment]
Thanks a lot. Can I expect some more help, regarding payment gateway
(instamojo) ? I am stuck over there.

**Comment by thyrlian** [comment]
Sorry @SunilThombare but that is out of my knowledge and off topic.  You should try ask on stackoverflow.

**Comment by SunilThombare** [comment]
Ok thanks, thanks a lot. Enjoy.

Sent from Mail for Windows 10
