### ISSUE TITLE
Unresolved reference: setTextInputLayoutErrorTextAppearance

### ISSUE THREAD

**Issue by Hitch** [thyrlian/AwesomeValidation#67]
all working fine , but TEXT_INPUT_LAYOUT having issue with setTextInputLayoutErrorTextAppearance
Check image below
![untitled](https://user-images.githubusercontent.com/16507765/43360708-b28debd2-92bb-11e8-8321-0582eb1bd5a8.jpg)

**Comment by thyrlian** [comment]
Hi @Hitch, you're right.  It's because `setTextInputLayoutErrorTextAppearance` is a new API which was added recently, and there is no release for that yet (sorry for my bad).   Nevertheless, you can still use the feature by importing the dependency as below (import the project commit including this code change):

```groovy
dependencies {
    implementation 'com.github.thyrlian:AwesomeValidation:1c6e59e1ba35ff0350dbd86dc42b9b1a45c0417f'
}
```

Thanks for reporting the issue, will release soon to "fix it".

**Comment by thyrlian** [comment]
Hi @Hitch, v4.2 was just tested and released.  You can simply grab [it](https://bintray.com/thyrlian/android-libraries/com.basgeekball.awesomevalidation/4.2) by:

```
implementation 'com.basgeekball:awesome-validation:4.2'
```
