### ISSUE TITLE
Email validation issue 

### ISSUE THREAD

**Issue by FALL1N1dev** [thyrlian/AwesomeValidation#88]
When there is space left in the email address edit text either at the start or end **_awesomeValidation.validate()_**  will return false even if the entered email address is correct. This is an issue esp.  when autofill option for the edit text is used. 
This could have been avoided if the data from edit text retrieved by the library is by editText.getText().toString().toTrim();

**Comment by thyrlian** [comment]
Hi @FALL1N1dev, thank you for raising it up.

So your concern is that the leading/trailing spaces are not trimmed off during validation.

By design, we'd like to do it this way (no trim).  I'll explain why below:
* There are cases where leading/trailing symbols(including spaces) are meaningful, we don't wanna make decisions on behalf of the developer who uses this library.
* **Consistency**: what if we trim the leading/trailing spaces during validation, but later when consuming the input text, the developer doesn't (or forgets to) trim the spaces?
* There is still plenty of freedom that the developers can give their own regex to the validation (e.g. with leading/trailing spaces in the regex).

That's the reason why we'd like to process only the **raw input**, instead of trimming anything.

Please let us know if you still have other concerns.  Thank you.

**Comment by thyrlian** [comment]
I'll close this issue if there is no further input.  Thanks.

**Comment by FALL1N1dev** [comment]
> 
@thyrlian 
No, I will customize the  regex used for validation. 
Thank you.
